---
title: "AtallahAnalysisPlan"
output: html_document
date: "2023-09-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Planned revisions to reproduction of Chakraborty (2021)
The paper which I aim to revise is entitled Social inequities in the distribution of COVID-19: An intra-categorical analysis of people with disabilities in the U.S. by J. Chakraborty (2021). 

## Analysis
1. I will revise the final map ("Race Model Weights") to fix the color ramp. This will involve changing one parameter in the code.
2. I will revise the table in the "Missing Data" section so that it displays properly. This will involve changing the table code.
3. I will revise the plot of "Percent Native American" and "COVID-19 Incidence" found at the end of the "Bivariate nonparametric correlation analysis" section to make outlier points easier to see.
4. I will revise the discussion section to create one single section; currently, it is split.
5. I will add a conclusion section which will state an opinion on whether the reproduction was successful and theorize implications for scientific knowledge.

## Results

1. The revised map will be shown in the same section as in the original paper (under "Interpret GEE Model").
2. The revised table will be shown in the same section as in the original paper (under "Missing Data).
3. The revised plot will be shown in the same section as in the original paper (at the end of "Bivariate nonparametric correlation analysis").
4. The content of the discussion section will be altered such that information from Emily's work will be incorporated into the existing, primary discussion.
5. The conclusion section will appear after the discussion section.

## Discussion

1. If the revised map has an improved color ramp, it may improve the ability of readers to understand the map and differentiate the classes. 
2. If the revised table is able to show all columns on the page, it will allow readers to view the data more effectively.
3. If the revised plot has darker points, it may enable readers to see outlier points more clearly and gain more information from the graph.
4. If this discussion section is made into one section, the structure of the paper will be made more clear and possibly concise.
5. If a well-developed conclusion is added, the structure of the paper will benefit in that there will be a section to summarize the perceived effectiveness of the reproduction study as well as how the work of the authors applies to how the scientific community may view the original study.
